# .github/workflows/chromatic.yml
# name of our action
name: 'Chromatic Deployment'
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: src/marsen.react
      - run: cd src/marsen.react && ls && yarn && yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} && ls
      #- name: Publish Storybook Chromatic
        #uses: chromaui/action@v1        
        # options required to the GitHub chromatic action        
        #with:          
          # our project token, to see how to obtain it
          # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
          #token: ${{ secrets.GITHUB_TOKEN }}
          #projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          #exitZeroOnChanges: true
          
