# .github/workflows/chromatic.yml
# name of our action
name: 'Chromatic Deployment'
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v2
      - run: cd ./src/marsen.react && yarn && yarn build && yarn build-storybook && yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
