on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Sonar Cloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      # support dotnet9.0
      uses: marsen/sonarscan-dotnet@v2.4.1
      with:
        # The key of the SonarQube project
        sonarProjectKey: Marsen.NetCore.Dojo
        # The name of the SonarQube project
        sonarProjectName: Marsen.NetCore.Dojo
        # The name of the SonarQube Organization
        sonarOrganization: marsen-github
        # Optional extra command arguments the the SonarScanner 'begin' command
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="./test/*/TestResults/*/coverage.opencover.xml"
        # Optional. Set to 1 or true to not run 'dotnet test' command
        # dotnetDisableTests: true
        dotnetTestArguments: Marsen.NetCore.Dojo.Integration.Test.sln --logger trx -p:CoverletOutputFormat="json%2copencover" --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        dotnetBuildArguments: Marsen.NetCore.Dojo.sln
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
