name: Stryker .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stryker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore tool
      run: dotnet tool restore      
    - name: Dotnet Stryker      
      run: dotnet stryker -s Marsen.NetCore.Dojo.Integration.Test.sln --dashboard-api-key=$STRYKER_DASHBOARD_API_KEY
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}  
