name: Stryker .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stryker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 8.0.x
    - name: Restore tool
      run: dotnet tool restore
    - name: Dotnet Stryker
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      run: |
        echo "DOTNET_ROOT=/opt/hostedtoolcache/dncs/8.0.101/x64" >> $GITHUB_ENV
        echo "/opt/hostedtoolcache/dncs/8.0.101/x64" >> $GITHUB_PATH
        dotnet stryker -s Marsen.NetCore.Dojo.Integration.Test.sln --dashboard-api-key=$STRYKER_DASHBOARD_API_KEY
