name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Npm install
      run: npm i --prefix src/Marsen.TypeScript.Dojo
    - name: Run Cover
      run: npm run cover --prefix src/Marsen.TypeScript.Dojo        
    - name: Setup Sonarqube
      uses: warchant/setup-sonar-scanner@v7      
    - name: Run Sonarqube
      run:  |
          java -version  # Verify Java version
          sonar-scanner \
          -Dsonar.organization=marsen-github \
          -Dsonar.projectKey=Marsen.TypeScript.Dojo \
          -Dsonar.sources=./src/Marsen.TypeScript.Dojo/src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=$SONAR_TS_LOGIN  \
          -Dsonar.typescript.lcov.reportPaths=src/Marsen.TypeScript.Dojo/coverage/lcov.info 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
      SONAR_TS_LOGIN: ${{ secrets.SONAR_TS_LOGIN }} 
