name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: Run LS
      run: ls src/Marsen.TypeScript.Dojo
    - name: Npm install
      run: npm i
    - name: Run Cover
      run: npm run cover --prefix src/Marsen.TypeScript.Dojo
    - name: npm link TypeScript
      run: npm link typescript          
    - name: Setup Sonarqube
      uses: warchant/setup-sonar-scanner@v1      
    - name: Run Sonarqube
      run:  sonar-scanner
          -Dsonar.organization=marsen-github 
          -Dsonar.projectKey=Marsen.TypeScript.Dojo
          -Dsonar.sources=./src/Marsen.TypeScript.Dojo/src
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=1ae1fa107fbe41368a6232fe92e388dffcc49fe5   

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
