name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master       
    - name: SonarScanner TSProject npm link
      run: npm link typescript          
    - name: SonarScanner TSProject Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1      
    - name: SonarScanner TSProject Run              
      run:  sonar-scanner
          -Dsonar.organization=marsen-github 
          -Dsonar.projectKey=Marsen.TypeScript.Dojo
          -Dsonar.sources=./src/Marsen.TypeScript.Dojo/src
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=1ae1fa107fbe41368a6232fe92e388dffcc49fe5   
