name: TypeScript

on:
  push:
    branches: [ master ]

jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: ls
      run: ls

