name: TypeScript

on:
  push:
    branches: [ master ]

jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: ls
      run: ls
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
          -Dsonar.organization=marsen-github 
          -Dsonar.projectKey=Marsen.TypeScript.Dojo 
          -Dsonar.sources=./Marsen.TypeScript.Dojo 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=1ae1fa107fbe41368a6232fe92e388dffcc49fe5
