name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master 
    - name: Npm install
      run: npm i --prefix src/Marsen.TypeScript.Dojo
    - name: Run Cover
      run: npm run cover --prefix src/Marsen.TypeScript.Dojo
    - name: npm link TypeScript
      run: npm link typescript          
    - name: Setup Sonarqube
      uses: warchant/setup-sonar-scanner@v1      
    - name: Run Sonarqube
      run:  sonar-scanner
          -Dsonar.organization=marsen-github 
          -Dsonar.projectKey=Marsen.TypeScript.Dojo 
          -Dsonar.sources=./src/Marsen.TypeScript.Dojo/src 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=3906bdd41eddb611327dcc05e950d94e987cff54 
          -Dsonar.typescript.lcov.reportPaths=src/Marsen.TypeScript.Dojo/coverage/lcov.info 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
      SONAR_TS_LOGIN: ${{ secrets.SONAR_TS_LOGIN }} 
